### ISSUE TITLE
Buerokratt Training Module API endpoints

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-onboarding#8]
AS A Developer
I WANT TO see the full list of Bürokratt's API endpoints
SO THAT I could re-use them where possible and know which ones are currently missing or need to be updated

> PS! This is a draft issue to mark endpoints on-the-go while grooming the issues. Will be refactored.

#### Training Module

**Ruuter**

> If Ruuter does not accept GET parameters as input (adding this functionality is in the backlog), use POST service instead

`/intents` to list Rasa intents

> Rasa intents originate from YAML files but are pipelined to and then read from OpenSearch

- [ ] GET service `/intents` without request parameters to list all intents, including confirmed (`.yml`) and in process (`.yml.tmp`) ones
- [ ] POST service `/intents` with POST body `intent_name = common_` to list all intents starting with `common_`
- [ ] [GET service `/intents/in-model`](https://github.com/buerokratt/Training-Module/issues/75) with `intent name` as request parameter to get a list of intents in model (in `domain.yml`)
- [ ] POST service `/intents/examples` with POST body `intent_name = common_greeting_ee` to list all examples for intent named `common_greeting_ee`
- [ ] [POST service `/intents/examples/add`](https://github.com/buerokratt/Training-Module/issues/79) to add new examples, input as POST parameters, accept JSON only, multiple examples can be used as input
- [ ] [POST service `/intents/examples/update`](https://github.com/buerokratt/Training-Module/issues/79) to update examples of an existing intent, input as POST parameters, accept JSON only, accepting `intent_name` as an intent name to change, `target` as an existing (to update) and `example` as an update example as POST parameters
- [ ] [POST service `/intents/examples/delete`](https://github.com/buerokratt/Training-Module/issues/79) to delete an existing example of an intent, input as POST parameters, accept JSON only, accepting `intent_name` as an intent name to change and `target` as an existing (to delete) as POST parameters
- [ ] GET service `/intents/history/last-modified/{intentID)`
- [ ] POST service `/intents/add` to add new intents, accepting `intent_name` as a POST parameter
- [ ] POST service `/intents/update` to update existing intents, accepting `target` as an existing (to update) and `intent_name` as a new intent name as a POST parameters
- [ ] POST service `/intents/delete` to delete existing intents, accepting `intent_name` as a POST parameter

_**Forms**_

- [ ] GET service `/rasa/forms` without request parameters to list all Rasa forms from `domain.yml`
- [ ] POST service `/rasa/forms` with a POST parameter "form_name" to fetch the full content of a specified form
- [ ] [POST service `/rasa/forms/search`](https://github.com/buerokratt/Training-Module/issues/95) with input parameters `type: slots/forms/responses` and `input: {JSON array}` 
- [ ] POST service `/rasa/forms/add` to add new Rasa forms, accepting `form_name` (text), `ignored_intents` (array) and `required_slots` (array) as POST parameters (input as JSON)
- [ ] POST service `/rasa/forms/update` to update an existing Rasa form, accepting `form_name` (text), `ignored_intents` (array) and `required_slots` (array) as POST parameters (input as JSON)
- [ ] POST service `/rasa/forms/delete` to delete an existing Rasa form, accepting `form_name` (text) as a POST parameter (input as JSON)

_**Slots**_

- [ ] GET service `/rasa/slots` without request parameters to list all Rasa slots from `domain.yml`
- [ ] POST service `/rasa/slots` with a POST parameter "slot_name" to fetch the full content of a specified form
- [ ] POST service `/rasa/slots/add` to add new Rasa slots, accepting `slot_name` (string), `mapping_type` (string - either `from_text`/`from_entity`), `mapping_entity` (string), `mapping_intent` (array), `mapping_not_intent` (array), `influence_conversation` (true/false)
- [ ] POST service `/rasa/slots/update` to update a slot Rasa form, accepting `slot_name` (string), `mapping_type` (string - either `from_text`/`from_entity`), `mapping_entity` (string), `mapping_intent` (array), `mapping_not_intent` (array), `influence_conversation` (true/false)
- [ ] POST service `/rasa/slots/delete` to delete an existing Rasa slot, accepting `slot_name` (text) as a POST parameter (input as JSON)

_**Responses**_

- [ ] GET service `/rasa/responses` without request parameters to list all Rasa responses from `domain.yml` in `responses`
- [ ] POST service `/rasa/responses` with a POST parameter "form_name" to fetch the full content of a specified form
- [ ] [POST service `/rasa/responses/add`](https://github.com/buerokratt/Training-Module/issues/92) to add new Rasa responses, accepting `response_name` (text) and `response` (text) as POST parameters (input as JSON)
- [ ] [POST service `/rasa/responses/update`](https://github.com/buerokratt/Training-Module/issues/93) to update an existing Rasa response, accepting `response_name` (text) and `response` (text) as POST parameters (input as JSON)
- [ ] [POST service `/rasa/response/delete`](https://github.com/buerokratt/Training-Module/issues/94) to delete an existing Rasa response
- [ ] [GET service `/rasa/responses/dependencies`](https://github.com/buerokratt/Training-Module/issues/99) to list all Rasa dependencies grouped by responses,

**Rules**

- [ ] [GET service `/rasa/rules`](https://github.com/buerokratt/Training-Module/issues/103) to fetch a list of Rasa rules
- [ ] [POST service `/rasa/rules`](https://github.com/buerokratt/Training-Module/issues/113) with a POST parameter "rule_name" to fetch the full content of a specified form
- [ ] [POST service `/rasa/rules/search`](https://github.com/buerokratt/Training-Module/issues/96) with input parameters `type: slots/forms/responses` and `input: {JSON array}`
- [ ] [POST service `/rasa/rules/add`](https://github.com/buerokratt/Training-Module/issues/111) to add new Rasa stories
- [ ] [POST service `/rasa/rules/update`](https://github.com/buerokratt/Training-Module/issues/114) to update an existing Rasa rule
- [ ] [POST service `/rasa/rules/delete`](https://github.com/buerokratt/Training-Module/issues/104) to delete an existing rule

**Stories**

- [ ] [GET service `/rasa/stories`](https://github.com/buerokratt/Training-Module/issues/102) to fetch a list of Rasa stories
- [ ] [POST service `/rasa/stories`](https://github.com/buerokratt/Training-Module/issues/112) with a POST parameter "story_name" to fetch the full content of a specified story
- [ ] [POST service `/rasa/stories/search`](https://github.com/buerokratt/Training-Module/issues/97) with input parameters `type: slots/forms/responses` and `input: {JSON array}`
- [ ] [POST service `/rasa/stories/add`](https://github.com/buerokratt/Training-Module/issues/110) to add new Rasa stories
- [ ] [POST service `/rasa/stories/update`](https://github.com/buerokratt/Training-Module/issues/115) to update an existing Rasa story
- [ ] [POST service `/rasa/stories/delete`](https://github.com/buerokratt/Training-Module/issues/109) to delete an existing rule

**Test stories**

- [ ] [GET service `/rasa/test-stories`](https://github.com/buerokratt/Training-Module/issues/105) to fetch a list of Rasa test stories
- [ ] [POST service `/rasa/test-stories`](https://github.com/buerokratt/Training-Module/issues/106) to fetch full content of a specified Rasa test story
- [ ] [POST service `/rasa/test-stories/links`](https://github.com/buerokratt/Training-Module/issues/116) to fetch a list of Rasa rules and stories with links to test stories
- [ ] [POST service `/rasa/test-stories/add`](https://github.com/buerokratt/Training-Module/issues/118) to add new Rasa test stories
- [ ] [POST service `/rasa/test-stories/update`](https://github.com/buerokratt/Training-Module/issues/117) to update an existing Rasa test story
- [ ] [POST service `/rasa/test-stories/delete`](https://github.com/buerokratt/Training-Module/issues/119) to delete an existing Rasa test story

**Entities**

- [ ] [GET service `/rasa/entities`](https://github.com/buerokratt/Training-Module/issues/120) to fetch a list of Rasa entities
- [ ] [POST service `/rasa/entities`](https://github.com/buerokratt/Training-Module/issues/127) to fetch full content of a specified Rasa entity
- [ ] [POST service `/rasa/entities/add`](https://github.com/buerokratt/Training-Module/issues/121) to add a new Rasa entity
- [ ] [POST service `/rasa/entities/update`](https://github.com/buerokratt/Training-Module/issues/128) to update an existing Rasa entity
- [ ] [POST service `/rasa/entities/delete`](https://github.com/buerokratt/Training-Module/issues/129) to delete an existing Rasa entity

**Regex**

- [ ] [GET service `/rasa/regex`](https://github.com/buerokratt/Training-Module/issues/124) to fetch a list of Rasa regexes
- [ ] [POST service `/rasa/regex`](https://github.com/buerokratt/Training-Module/issues/125) to fetch full content of a specified Rasa regex
- [ ] [POST service `/rasa/regex/example`](https://github.com/buerokratt/Training-Module/issues/130) to fetch full content of a specified example within a specified Rasa regex

**Examples**

- [ ] GET service `/rasa/examples` to list all Rasa examples
- [ ] GET service `/rasa/examples/entities` to list all Rasa examples
- [ ] [POST service `/rasa/examples/entities`](https://github.com/buerokratt/Training-Module/issues/126) to list all Rasa intents with examples containing a specified entity

**Config**

- [ ] [GET REST endpoint `/rasa/config`](https://github.com/buerokratt/Training-Module/issues/101) to read the content of Rasa NLU Model Configurations (`config.yml`)
- [ ] [POST REST endpoint `/rasa/config/update`](https://github.com/buerokratt/Training-Module/issues/100) to apply changes on Rasa NLU Model Configurations (`config.yml`)

**Rasa training**

- [ ] [GET endpoint `/rasa/training/results`](https://github.com/buerokratt/Training-Module/issues/131) to fetch a list of training results for trained models
- [ ] [GET endpoint `/rasa/training/results/files`](https://github.com/buerokratt/Training-Module/issues/132) to fetch a list of all test results files of a specified trained model
- [ ] [POST endpoint `/rasa/training/results/files`](https://github.com/buerokratt/Training-Module/issues/133) to fetch the full content of a test result file of a specified trained model

**Nodejs**

`/convert` to convert one filetype to another. See https://github.com/buerokratt/Training-Module/issues/45 for more.

- [ ] `/convert/yaml-to-json`
- [ ] `/convert/json-to-yaml`
- [ ] `/convert/csv-to-json`

`/file` to manipulate text files. See https://github.com/buerokratt/Training-Module/issues/44 for more.

- [ ] `/file/create` to create a new text file
- [ ] `/file/change` to change the content of an existing text file
- [ ] `/file/delete` to delete an existing text file

**Metrics**

- [ ] [GET service `/metrics/intents`](https://github.com/buerokratt/Analytics-Module/issues/39) for a count of intents identified, grouped by intents
- [ ] [POST endpoint `/metrics/intents`](https://github.com/buerokratt/Buerokratt-onboarding/issues/8) with intent name as a POST parameter for a count of a specific intent being used
